# Generated by Django 5.1.6 on 2025-02-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.CharField(default='media/images', max_length=255),
        ),
    ]
