from .area import AreaViewSet
from .access import AccessViewSet
from .course import CourseViewSet
from .course_member import CourseMemberViewSet
from .member_tag import MemberTagViewSet
from .member import MemberViewSet
from .project import ProjectViewSet
from .new import NewViewSet
from .tag import TagViewSet