from .area import AreaViewSet
from .access import AccessViewSet
from .course import CourseViewSet
from .course_user import CourseUserViewSet
from .esp_tag import EspTagListAPIView
from .user_tag import UserTagViewSet
from .project import ProjectViewSet
from .new import NewViewSet
from .tag import TagViewSet