# Generated by Django 5.1.6 on 2025-02-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('social_medias', models.JSONField()),
                ('type', models.CharField(choices=[('Docente', 'Docente'), ('Discente', 'Discente'), ('TAE', 'Tae'), ('Externo', 'Externo')], max_length=20)),
                ('state', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Egresso', 'Egresso')], max_length=20)),
                ('biography', models.TextField()),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area', to='portal.course')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_member', to='portal.course')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_member', to='portal.member')),
            ],
            options={
                'verbose_name': 'course_member',
                'verbose_name_plural': 'course_members',
                'db_table': 'course_member',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initial_date', models.DateField(auto_now_add=True)),
                ('final_date', models.DateField()),
                ('areas', models.JSONField()),
                ('state', models.CharField(choices=[('Não Iniciado', 'Nao Iniciado'), ('Em Desenvolvimento', 'Desenvolvimento'), ('Concluído', 'Concluido'), ('Cancelado', 'Cancelado')], max_length=255)),
                ('deploy_link', models.URLField()),
                ('front_repo_link', models.URLField()),
                ('back_repo_link', models.URLField()),
                ('design_link', models.URLField()),
                ('about', models.TextField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor', to='portal.member')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
            },
        ),
    ]
