# Generated by Django 5.1.6 on 2025-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
