# Generated by Django 5.1.6 on 2025-10-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_member_social_media_remove_project_areas_and_more'),
        ('portal', '0006_alter_project_initial_date'),
    ]

    operations = [
    ]
