# Generated by Django 5.1.6 on 2025-10-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_merge_20251002_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tag',
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.AlterField(
            model_name='member',
            name='biography',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='final_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.JSONField(),
        ),
    ]
