# Generated by Django 5.1.6 on 2025-10-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_tag_remove_member_email_alter_member_biography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Autorizado'), (2, 'Não autorizado'), (3, 'Não cadastrado')])),
                ('type', models.IntegerField(choices=[(1, 'Tag'), (2, 'App')])),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='portal.tag')),
            ],
            options={
                'verbose_name': 'access',
                'verbose_name_plural': 'access',
                'db_table': 'access',
            },
        ),
    ]
