# Generated by Django 5.1.6 on 2025-10-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_tag', to='portal.member')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_tag', to='portal.tag')),
            ],
            options={
                'verbose_name': 'member_tag',
                'verbose_name_plural': 'member_tags',
                'db_table': 'member_tag',
            },
        ),
    ]
