# Generated by Django 5.1.6 on 2025-11-11 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_membrertag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrertag',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membrertag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_year', models.IntegerField()),
                ('final_year', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_user', to='portal.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course_user',
                'verbose_name_plural': 'course_users',
                'db_table': 'course_user',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tag', to='portal.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_tag',
                'verbose_name_plural': 'user_tags',
                'db_table': 'user_tag',
            },
        ),
        migrations.DeleteModel(
            name='CourseMember',
        ),
        migrations.DeleteModel(
            name='MembrerTag',
        ),
    ]
