# Generated by Django 5.2.1 on 2025-12-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_merge_20251205_1939'),
        ('portal', '0011_remove_membrertag_member_remove_membrertag_tag_and_more'),
    ]

    operations = [
    ]
